name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test Entry
        run: go test -C ./services/entry

      - name: Build Entry
        run: go build -C ./services/entry

      - name: Test Catalogue
        run: go test -C ./services/catalogue

      - name: Build Catalogue
        run: go build -C ./services/catalogue

      - name: Test Review
        run: go test -C ./services/review/cmd/api

      - name: Build Review
        run: go build -C ./services/review/cmd/api

      - name: Test Auth
        run: go test -C ./services/auth

      - name: Build Auth
        run: go build -C ./services/auth
